export enum Context {
  CENTERS = 'CENTERS',
  // ALL_CENTERS = 'ALL_CENTERS',
  // SPECIFIC_CENTER = 'SPECIFIC_CENTER',
  PERMISSIONS = 'PERMISSIONS',
  RESOURCES = 'RESOURCES',
  ASSIGNMENTS = 'ASSIGNMENTS',
  BOOKS = 'BOOKS'
}
