//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.21 at 04:17:12 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://perscholas.org/springbootsoapexample", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.perscholas.springbootsoapexample;
