-- MySQL Script generated by MySQL Workbench
-- 03/13/15 23:54:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema videoStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema videoStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videoStore` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `videoStore` ;

-- -----------------------------------------------------
-- Table `videoStore`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videoStore`.`customer` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Address` LONGTEXT NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videoStore`.`table_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videoStore`.`table_video` (
  `Video_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` TEXT(50) NOT NULL,
  `Category` VARCHAR(20) NOT NULL,
  `Time` INT NOT NULL,
  `Actors` VARCHAR(90) NULL,
  `Director` VARCHAR(20) NULL,
  PRIMARY KEY (`Video_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videoStore`.`Rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videoStore`.`Rental` (
  `customer_id` INT UNSIGNED NOT NULL,
  `video_id` INT UNSIGNED NOT NULL,
  `Check_out_date` DATE NOT NULL,
  `Is_it_returned` ENUM('Y','N') NULL,
  `Returned_date` DATE NOT NULL,
  `rental_charges` INT UNSIGNED NOT NULL,
  `due_date` DATE NOT NULL,
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `video_id_idx` (`video_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `videoStore`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_id`
    FOREIGN KEY (`video_id`)
    REFERENCES `videoStore`.`table_video` (`Video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
